import Link from 'next/link'
import style from './index.module.scss'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Banner from '../components/Banner'

export default function Terms() {

    return (

        <>
            <Banner />

            <Header />

            <main className="container mx-auto pt-4 text-white">

                <div className="py-12 sm:py-10">
                    <div className="mx-auto max-w-7xl px-6 lg:px-8">
                        <h2 className="text-center text-xl font-semibold leading-8 text-gray-100">
                            TERMS &amp; CONDITIONS</h2>
                        <p className="terms-description">
                            MiDiPunkz is a collection of digital artworks (NFTs) running on the Ethereum network. This website is only an interface allowing participants to exchange digital collectibles. Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by this website before approval. Furthermore, as the MiDiPunkz smart contract runs on the Ethereum network, there is no ability to undo, reverse, or restore any transactions.</p>
                        <p className="terms-description">This website and its connected services are provided “as is” and “as available” without warranty of any kind. By using this website you are accepting sole responsibility for any and all transactions involving MiDiPunkz digital collectibles. </p>
                        <h2 className="text-center text-lg font-semibold leading-8 text-gray-100">
                            OWNERSHIP</h2>
                        <p className="terms-description">i. You Own the NFT. Each MiDiPunkz is an NFT on the Ethereum blockchain. When you purchase an NFT, you own the underlying MiDiPunkz, the Art, completely. Ownership of the NFT is mediated entirely by the Smart Contract and the Ethereum Network: at no point may we seize, freeze, or otherwise modify the ownership of any MiDiPunkz.</p>
                        <p className="terms-description">ii. Personal Use. Subject to your continued compliance with these Terms, SongsOfEden & Prizem Labs grants you a worldwide, royalty-free license to use, copy, and display the purchased Art, along with any extensions that you choose to create or use, solely forthe following purposes: (i) for your own personal, non-commercial use; (ii) as part of a marketplace that permits the purchase and sale of your MiDiPunkz / NFT, provided that the marketplace cryptographically verifies each MiDiPunkz owner’s rights to display the Art for their MiDiPunkz to ensure that only the actual owner can display the Art; or (iii) as part of a third party website or application that permits the inclusion, involvement, or participation of your MiDiPunkz, provided that the website/application cryptographically verifies each MiDiPunkz owner’s rights to display the Art for their MiDiPunkz to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner ofthe MiDiPunkz leaves the website/application.</p>
                        <p className="terms-description">iii. Commercial Use. Subject to your continued compliance with these Terms, SongsOfEden x Prizem Labs grants you an unlimited, worldwide license to use, copy, and display the purchased Art for the purpose of creating derivative works based upon the Art (“Commercial Use”). Examples of such Commercial Use would e.g. be the use of the Art to produce and sell merchandise products (T-Shirts etc.) displaying copies of the Art. For the sake of clarity, nothing in this Section will be deemed to restrict you from (i) owning or operating a marketplace that permits the use and sale of MiDiPunkzs generally, provided that the marketplace cryptographically verifies eachMiDiPunkz owner’s rights to display the Art for their MiDiPunkz to ensure that only the actual owner can display the Art; (ii) owning or operating a third party website or application that permits the inclusion, involvement, or participation of MiDiPunkzs generally, provided that the third party website or application cryptographically verifies each MiDiPunkz owner’s rights to display the Art for theirMiDiPunkz to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the Purchased MiDiPunkz leaves the website/application; or (iii) earning revenue from any of the foregoing.</p>
                    </div></div>
            </main>
            <Footer />
        </>

    )
}
